AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
LineLength:
  Max: 120
ClassVars:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
MethodLength:
  Max: 17
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 9
