AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'example/**/*'
ClassVars:
  Enabled: false
LineLength:
  Max: 120
MethodLength:
  Max: 18
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 9
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - lib/cms_scanner/finders/finder.rb
Style/MixinUsage:
  Exclude:
    - lib/cms_scanner/formatter.rb
